Repository DSpotDevelopers/dspot-erp, pull requests merged in 2025-06, with the labels that each got.

#25 GZY-275: Retrieve original ever gauzy license for compliance and permission
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSES.md
  README.md
  SECURITY.md
  apps/desktop-timer/src/package.json
  apps/desktop/README.md
  apps/desktop/src/package.json
  apps/server-api/src/package.json
  apps/server/README.md
  apps/server/src/package.json
  packages/auth/README.md
  packages/common/README.md
  packages/config/README.md
  packages/contracts/README.md
  packages/core/src/lib/time-tracking/time-log/time-log.service.ts
  packages/core/src/lib/time-tracking/timer/timer-weekly-limit.service.ts
  packages/metrics/README.md
  packages/plugin/README.md
  packages/plugins/changelog/README.md
  packages/plugins/integration-ai-ui/README.md
  packages/plugins/integration-ai/README.md
  packages/plugins/integration-hubstaff/README.md
  packages/plugins/integration-upwork/README.md
  packages/plugins/job-employee-ui/README.md
  packages/plugins/knowledge-base/README.md
  packages/plugins/onboarding-ui/README.md
  packages/plugins/product-reviews/README.md
  packages/plugins/public-layout-ui/README.md
  packages/plugins/sentry-tracing/README.md
  packages/ui-auth/README.md
  packages/ui-config/README.md
  packages/ui-core/README.md
  packages/ui-core/i18n/assets/i18n/ach.json
  packages/ui-core/i18n/assets/i18n/ar.json
  packages/ui-core/i18n/assets/i18n/bg.json
  packages/ui-core/i18n/assets/i18n/de.json
  packages/ui-core/i18n/assets/i18n/en.json
  packages/ui-core/i18n/assets/i18n/es.json
  packages/ui-core/i18n/assets/i18n/fr.json
  packages/ui-core/i18n/assets/i18n/he.json
  packages/ui-core/i18n/assets/i18n/it.json
  packages/ui-core/i18n/assets/i18n/nl.json
  packages/ui-core/i18n/assets/i18n/pl.json
  packages/ui-core/i18n/assets/i18n/pt.json
  packages/ui-core/i18n/assets/i18n/ru.json
  packages/ui-core/i18n/assets/i18n/zh.json
  packages/ui-core/shared/src/lib/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
Labels: Feature, Ready to be Merged

#26 GZY-277: Set default weekly limit to 40 hours for new users
  packages/contracts/src/lib/employee.model.ts
  packages/core/src/lib/employee/commands/handlers/employee.create.handler.ts
  packages/ui-core/shared/src/lib/employee/employee-rates/employee-rates.component.ts
Labels: Feature, Ready to be Merged

#27 feat: set default weekly limit to 40 hours for new users by invitation
  packages/core/src/lib/invite/commands/handlers/invite.accept-employee.handler.ts
Labels: Feature, Ready to be Merged

#28 GZY-276: Add fork notice and modification summary to readme
  CHANGELOG.md
  README.md
  packages/common/CHANGELOG.md
  packages/contracts/CHANGELOG.md
  packages/desktop-ui-lib/CHANGELOG.md
  packages/plugins/integration-upwork/CHANGELOG.md
  packages/plugins/onboarding-ui/CHANGELOG.md
  packages/ui-auth/CHANGELOG.md
  packages/ui-core/CHANGELOG.md
  packages/utils/CHANGELOG.md
  yarn.lock
Labels: Documentation, Feature, Ready to Review

#29 GZY-281: Secure project management editor by replacing ck editor with ngx editor
  CHANGELOG.md
  apps/gauzy/package.json
  packages/desktop-ui-lib/package.json
  packages/plugins/job-proposal-ui/package.json
  packages/plugins/job-search-ui/package.json
  packages/plugins/public-layout-ui/package.json
  packages/ui-core/core/src/lib/components/base-nav-menu/base-nav-menu.component.ts
  packages/ui-core/package.json
  packages/ui-core/shared/src/index.ts
  packages/ui-core/shared/src/lib/project-module/project-module-mutation/project-module-mutation.component.html
  packages/ui-core/shared/src/lib/project-module/project-module-mutation/project-module-mutation.component.ts
  packages/ui-core/shared/src/lib/project-module/project-module-mutation/project-module-mutation.module.ts
  packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.component.html
  packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.component.ts
  packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.module.ts
  packages/ui-core/shared/src/lib/rich-text-editor/index.ts
  packages/ui-core/shared/src/lib/rich-text-editor/rich-text-editor.component.html
  packages/ui-core/shared/src/lib/rich-text-editor/rich-text-editor.component.scss
  packages/ui-core/shared/src/lib/rich-text-editor/rich-text-editor.component.ts
  packages/ui-core/shared/src/lib/rich-text-editor/rich-text-editor.module.ts
  yarn.lock
Labels: Feature, Ready to be Merged

#30 GZY-282: Secure employee management editor by replacing CKEditor with ngx-editor
  apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.html
  apps/gauzy/src/app/pages/employees/edit-employee/edit-employee-profile/edit-employee-employment/edit-employee-employment.component.ts
  apps/gauzy/src/app/pages/employees/employees.module.ts
  packages/plugins/public-layout-ui/src/lib/components/mutation/public-page-employee-mutation/public-page-employee-mutation.component.html
  packages/plugins/public-layout-ui/src/lib/components/mutation/public-page-employee-mutation/public-page-employee-mutation.component.ts
  packages/plugins/public-layout-ui/src/lib/public-layout.module.ts
  packages/ui-core/shared/src/lib/rich-text-editor/rich-text-editor.component.ts
Labels: Feature, Ready to be Merged

#32 GZY-263: Fix administrator registration time
  apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
  apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
  packages/core/src/lib/time-tracking/time-log/time-log.service.ts
  packages/core/src/lib/time-tracking/timer/timer-weekly-limit.service.ts
  packages/core/src/lib/time-tracking/timer/timer.service.ts
Labels: Bugfix, Ready to be Merged

#33 feat: employee role cannot view or update all tasks in assigned projects
  apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
  apps/gauzy/src/app/pages/teams/teams-mutation/teams-mutation.component.ts
  packages/core/src/lib/tasks/task.service.ts
  packages/core/src/lib/user-organization/user-organization.services.ts
  packages/ui-core/shared/src/lib/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
Labels: Feature, Ready to be Merged

#34 GZY-200: Task name with only spaces is allowed
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
  apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.html
  apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
  packages/plugins/public-layout-ui/src/lib/public-layout.module.ts
  packages/ui-core/i18n/assets/i18n/ach.json
  packages/ui-core/i18n/assets/i18n/ar.json
  packages/ui-core/i18n/assets/i18n/bg.json
  packages/ui-core/i18n/assets/i18n/de.json
  packages/ui-core/i18n/assets/i18n/en.json
  packages/ui-core/i18n/assets/i18n/es.json
  packages/ui-core/i18n/assets/i18n/fr.json
  packages/ui-core/i18n/assets/i18n/he.json
  packages/ui-core/i18n/assets/i18n/it.json
  packages/ui-core/i18n/assets/i18n/nl.json
  packages/ui-core/i18n/assets/i18n/pl.json
  packages/ui-core/i18n/assets/i18n/pt.json
  packages/ui-core/i18n/assets/i18n/ru.json
  packages/ui-core/i18n/assets/i18n/zh.json
  packages/ui-core/shared/src/lib/shared.module.ts
  packages/ui-core/shared/src/lib/tasks/add-task-dialog/add-task-dialog.component.html
  packages/ui-core/shared/src/lib/tasks/add-task-dialog/add-task-dialog.component.ts
Labels: Bugfix, Ready to be Merged

#35 GZY-29: Back arrow button navigates via browser history instead of redirecting to employee list
  apps/gauzy/src/app/pages/employees/edit-employee/edit-employee.component.html
  packages/ui-core/shared/src/lib/components/back-navigation/back-navigation.component.ts
Labels: Bugfix, Ready to be Merged

#38 GZY-139: Improve readability for manual time entry and editing in dark mode
  packages/ui-core/shared/src/lib/timer-picker/manual-timer-picker/manual-timer-picker.component.scss
Labels: Feature, Ready to be Merged

#41 GZY-217: Fix sorting logic for tasks dashboard
  apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
Labels: Bugfix, Ready to be Merged

#6 GZY-236: Fix time log boundary
  apps/gauzy/src/app/pages/employees/timesheet/calendar/calendar/calendar.component.ts
  apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.html
  apps/gauzy/src/app/pages/employees/timesheet/daily/daily/daily.component.ts
  apps/gauzy/src/app/pages/employees/timesheet/view/view/view.component.ts
  apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.html
  apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
  packages/contracts/src/lib/timesheet.model.ts
  packages/core/src/lib/time-tracking/time-log/commands/handlers/delete-time-span.handler.ts
  packages/core/src/lib/time-tracking/time-log/commands/handlers/time-log-delete.handler.ts
  packages/core/src/lib/time-tracking/time-log/commands/time-log-delete.command.ts
  packages/core/src/lib/time-tracking/time-log/dto/delete-time-log.dto.ts
  packages/core/src/lib/time-tracking/time-log/dto/manual-time-log.dto.ts
  packages/core/src/lib/time-tracking/time-log/time-log.entity.ts
  packages/core/src/lib/time-tracking/time-log/time-log.service.ts
  packages/core/src/lib/time-tracking/time-log/time-log.utils.ts
  packages/core/src/lib/time-tracking/time-slot/commands/handlers/time-slot-bulk-delete.handler.ts
  packages/ui-core/shared/src/lib/timer-picker/timer-range-picker/timer-range-picker.component.ts
  packages/ui-core/shared/src/lib/timesheet/edit-time-log-modal/edit-time-log-modal.component.html
  packages/ui-core/shared/src/lib/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
  packages/ui-core/shared/src/lib/timesheet/screenshots/view-screenshots-modal/view-screenshots-modal.component.ts
  packages/ui-core/shared/src/lib/timesheet/view-time-log-modal/view-time-log-modal.component.html
  packages/ui-core/shared/src/lib/timesheet/view-time-log-modal/view-time-log-modal.component.ts
  packages/ui-core/shared/src/lib/timesheet/view-time-log/view-time-log.component.html
  packages/ui-core/shared/src/lib/timesheet/view-time-log/view-time-log.component.ts
Labels: Bugfix, Ready to be Merged
