Repository DSpotDevelopers/dspot-erp, pull requests merged in 2025-05, with the labels that each got.

#1 Update GitHub workflows
  .github/workflows/api-dependencies.yml
  .github/workflows/aws-deploy-api.yml
  .github/workflows/aws-deploy-webapp.yml
  .github/workflows/linter.yml
  .github/workflows/webapp-dependencies.yml
Labels: devops

#2 GZY-235: Fix task filters
  packages/core/src/lib/tasks/task.service.ts
Labels: Bugfix, Ready to be Merged

#3 Fix Google url and revert CI variables
  .github/workflows/api-dependencies.yml
  .github/workflows/aws-deploy-api.yml
  .github/workflows/aws-deploy-webapp.yml
  .github/workflows/webapp-dependencies.yml
  packages/auth/src/lib/google/google.controller.ts
Labels: Bugfix, Ready to be Merged

#5 GZY-244: Fix stop timer error when timer context is not synced
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
Labels: Bugfix, Ready to be Merged

#4 GZY-242: Fix memory crash on task creation
  .env.compose
  .env.demo.compose
  .env.docker
  .env.local
  .env.sample
  packages/config/src/lib/database-helpers.ts
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
  packages/ui-core/shared/src/lib/tasks/add-task-dialog/add-task-dialog.component.html
Labels: Bugfix, Ready to be Merged

#8 fix: Fix desktop app compilation
  packages/desktop-ui-lib/src/lib/logo/logo.component.ts
  packages/desktop-ui-lib/src/lib/logo/logo.module.ts
Labels: Bugfix, Ready to be Merged

#7 GZY-192: Fix timer not stopped when task/project is removed or unassigned
  packages/contracts/src/lib/timesheet.model.ts
  packages/core/src/lib/time-tracking/timer/timer.service.ts
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
  packages/ui-core/i18n/assets/i18n/ar.json
  packages/ui-core/i18n/assets/i18n/bg.json
  packages/ui-core/i18n/assets/i18n/de.json
  packages/ui-core/i18n/assets/i18n/en.json
  packages/ui-core/i18n/assets/i18n/es.json
  packages/ui-core/i18n/assets/i18n/fr.json
  packages/ui-core/i18n/assets/i18n/he.json
  packages/ui-core/i18n/assets/i18n/it.json
  packages/ui-core/i18n/assets/i18n/nl.json
  packages/ui-core/i18n/assets/i18n/pl.json
  packages/ui-core/i18n/assets/i18n/pt.json
  packages/ui-core/i18n/assets/i18n/ru.json
  packages/ui-core/i18n/assets/i18n/zh.json
  packages/ui-core/shared/src/lib/time-tracker/components/time-tracker-status/time-tracker-status.service.ts
Labels: Bugfix, Changes Requested, Ready to be Merged

#9 GZY-233/GZY-229: Fix UI filters
  .env.local
  apps/gauzy/src/app/pages/projects/components/project-list/list.component.ts
  apps/gauzy/src/app/pages/tasks/components/task/task.component.ts
  nx.json
  packages/auth/package.json
  packages/common/package.json
  packages/contracts/src/index.ts
  packages/contracts/src/lib/smart-table-filters.model.ts
  packages/core/src/lib/organization-project/organization-project.service.ts
  packages/desktop-core/package.json
  packages/desktop-lib/package.json
  packages/desktop-ui-lib/package.json
  packages/desktop-ui-lib/src/lib/logo/logo.module.ts
  packages/desktop-window/package.json
  packages/plugin/package.json
  packages/ui-core/common/src/lib/utils/shared-utils.ts
  packages/ui-core/shared/src/lib/smart-data-layout/pagination/pagination-filter-base.component.ts
  packages/ui-core/shared/src/lib/table-filters/date-filter.component.ts
  packages/ui-core/shared/src/lib/table-filters/input-filter.component.ts
  packages/ui-core/shared/src/lib/table-filters/organization-team-filter.component.ts
  packages/ui-core/shared/src/lib/table-filters/tags-color-filter.component.ts
  packages/ui-core/shared/src/lib/table-filters/task-status-filter.component.ts
  packages/ui-core/shared/src/lib/tags/tags-color-input/tags-color-input.component.ts
  packages/ui-core/shared/src/lib/tasks/task-status-select/task-status-select.component.ts
Labels: Bugfix, Ready to be Merged

#10 Bugfix: Project with only spaces can be created
  packages/ui-core/core/src/lib/validators/empty-string.validator.ts
  packages/ui-core/core/src/lib/validators/index.ts
  packages/ui-core/i18n/assets/i18n/ach.json
  packages/ui-core/i18n/assets/i18n/ar.json
  packages/ui-core/i18n/assets/i18n/bg.json
  packages/ui-core/i18n/assets/i18n/de.json
  packages/ui-core/i18n/assets/i18n/en.json
  packages/ui-core/i18n/assets/i18n/es.json
  packages/ui-core/i18n/assets/i18n/fr.json
  packages/ui-core/i18n/assets/i18n/he.json
  packages/ui-core/i18n/assets/i18n/it.json
  packages/ui-core/i18n/assets/i18n/nl.json
  packages/ui-core/i18n/assets/i18n/pl.json
  packages/ui-core/i18n/assets/i18n/pt.json
  packages/ui-core/i18n/assets/i18n/ru.json
  packages/ui-core/i18n/assets/i18n/zh.json
  packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.component.ts
Labels: Bugfix, Ready to be Merged

#11 Bugfix: Fix missing client-side validation for required Status field on …
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.scss
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
  apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.html
  apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.scss
  apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
  packages/ui-core/shared/src/lib/tasks/add-task-dialog/add-task-dialog.component.html
  packages/ui-core/shared/src/lib/tasks/add-task-dialog/add-task-dialog.component.scss
  packages/ui-core/shared/src/lib/tasks/add-task-dialog/add-task-dialog.component.ts
Labels: Bugfix, Ready to be Merged

#12 GZY-228: Missing client side validation for required status field on task creation
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
  apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.html
  apps/gauzy/src/app/pages/tasks/components/team-task-dialog/team-task-dialog.component.ts
Labels: Bugfix, Ready to be Merged

#13 GZY-241: Clicking project card header unintentionally changes visibility
  apps/gauzy/src/app/pages/projects/components/project-list/list.component.html
  apps/gauzy/src/app/pages/projects/components/project-list/list.component.ts
  packages/ui-core/i18n/assets/i18n/ach.json
  packages/ui-core/i18n/assets/i18n/en.json
  packages/ui-core/i18n/assets/i18n/fr.json
  packages/ui-core/shared/src/lib/card-grid/card-grid-custom.component.ts
  packages/ui-core/shared/src/lib/card-grid/card-grid-with-init-function/card-grid-with-init-function.component.html
  packages/ui-core/shared/src/lib/card-grid/card-grid-with-init-function/card-grid-with-init-function.component.scss
  packages/ui-core/shared/src/lib/card-grid/card-grid-with-init-function/card-grid-with-init-function.component.ts
  packages/ui-core/shared/src/lib/card-grid/card-grid.module.ts
  packages/ui-core/shared/src/lib/card-grid/card-grid/card-grid.component.html
  packages/ui-core/shared/src/lib/card-grid/card-grid/card-grid.component.scss
  packages/ui-core/shared/src/lib/card-grid/card-grid/card-grid.component.ts
  packages/ui-core/shared/src/lib/card-grid/index.ts
  packages/ui-core/shared/src/lib/table-components/project-organization-grid/project-organization-grid.component.html
  packages/ui-core/shared/src/lib/table-components/project-organization-grid/project-organization-grid.component.ts
  packages/ui-core/shared/src/lib/table-components/visibility/visibility.component.html
  packages/ui-core/shared/src/lib/table-components/visibility/visibility.component.ts
Labels: Bugfix, Ready to be Merged

#14 GZY-227: Fix time entries changes not reflected in weekly view until manual page refresh
  apps/gauzy/src/app/pages/employees/timesheet/weekly/weekly/weekly.component.ts
  packages/ui-core/core/src/lib/services/timesheet/index.ts
  packages/ui-core/core/src/lib/services/timesheet/time-log-event.service.ts
  packages/ui-core/shared/src/lib/timesheet/edit-time-log-modal/edit-time-log-modal.component.ts
  packages/ui-core/shared/src/lib/timesheet/view-time-log-modal/view-time-log-modal.component.ts
  packages/ui-core/shared/src/lib/timesheet/view-time-log/view-time-log.component.ts
Labels: Bugfix, Ready to be Merged

#15 GZY-257: Fix missing auto-assignment of task creator in My Task creation
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.html
  apps/gauzy/src/app/pages/tasks/components/my-task-dialog/my-task-dialog.component.ts
  packages/ui-core/shared/src/lib/tasks/add-task-dialog/add-task-dialog.component.ts
Labels: Bugfix, Ready to be Merged

#16 GZY-185, GZY-193, GZY-194, GZY-189: Fix stop timer when project or task are deleted
  packages/contracts/src/lib/organization-projects.model.ts
  packages/contracts/src/lib/timesheet.model.ts
  packages/core/src/lib/time-tracking/timer/timer.module.ts
  packages/core/src/lib/time-tracking/timer/timer.service.ts
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
  packages/ui-core/i18n/assets/i18n/ach.json
  packages/ui-core/i18n/assets/i18n/ar.json
  packages/ui-core/i18n/assets/i18n/bg.json
  packages/ui-core/i18n/assets/i18n/de.json
  packages/ui-core/i18n/assets/i18n/en.json
  packages/ui-core/i18n/assets/i18n/es.json
  packages/ui-core/i18n/assets/i18n/fr.json
  packages/ui-core/i18n/assets/i18n/he.json
  packages/ui-core/i18n/assets/i18n/it.json
  packages/ui-core/i18n/assets/i18n/nl.json
  packages/ui-core/i18n/assets/i18n/pl.json
  packages/ui-core/i18n/assets/i18n/pt.json
  packages/ui-core/i18n/assets/i18n/ru.json
  packages/ui-core/i18n/assets/i18n/zh.json
  packages/ui-core/shared/src/lib/time-tracker/components/time-tracker-status/time-tracker-status.service.ts
Labels: Bugfix, Ready to be Merged

#18 GZY-267: Project selection component has fixed height causing selected projects to be hidden
  apps/gauzy/src/app/pages/invoices/invoice-add/by-organization/invoice-add-by-organization.component.scss
  apps/gauzy/src/app/pages/invoices/invoice-edit/by-role/invoice-edit-by-role.component.scss
  apps/gauzy/src/app/pages/invoices/invoice-email/invoice-email-mutation.component.scss
  packages/ui-core/shared/src/lib/employee/edit-employee-membership-form/edit-employee-membership-form.component.html
  packages/ui-core/shared/src/lib/employee/edit-employee-membership-form/edit-employee-membership-form.component.scss
  packages/ui-core/shared/src/lib/employee/employee-multi-select/employee-multi-select.component.scss
  packages/ui-core/shared/src/lib/time-tracker/time-tracker/time-tracker.component.scss
  packages/ui-core/shared/src/lib/timer-picker/timer-range-picker/timer-range-picker.component.scss
  packages/ui-core/shared/src/lib/timesheet/edit-time-log-modal/edit-time-log-modal.component.scss
Labels: Bugfix, Ready to be Merged

#19 GZY-264: Required fields not marked with asterisk
  packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.component.html
  packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.component.scss
  packages/ui-core/shared/src/lib/project/project-mutation/project-mutation.component.ts
Labels: Bugfix, Ready to be Merged
