Repository DSpotDevelopers/dspot-erp, pull requests merged in 2025-08, with the labels that each got.

#64 GZY-380: fix delete time-log silently fails with 200 status and no log de…
  packages/core/src/lib/time-tracking/time-log/commands/handlers/time-log-delete.handler.ts
  packages/core/src/lib/time-tracking/time-log/commands/handlers/time-log-update.handler.ts
  packages/core/src/lib/time-tracking/time-log/time-log.service.ts
  packages/core/src/lib/time-tracking/timer/timer.service.ts
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
Labels: Bugfix, Test, Ready to be Merged

#66 GZY-380: Fix remove broken timeLogs
  packages/core/src/lib/time-tracking/time-log/commands/handlers/time-log-delete.handler.ts
  packages/core/src/lib/time-tracking/time-log/time-log.service.ts
Labels: Bugfix, Ready to be Merged

#68 chore: update import from moment-timezone
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
Labels: Chore, Ready to be Merged

#63 E2e/379 get running all scheduled tests in the pipeline twice per day
  apps/gauzy-e2e/src/e2e/AddEmployeeLevelTest.ts
  apps/gauzy-e2e/src/e2e/AddTasksTest.ts
  apps/gauzy-e2e/src/e2e/GoalsTest.ts
  apps/gauzy-e2e/src/e2e/ManageEmployeesTest.ts
  apps/gauzy-e2e/src/e2e/OrganizationProjectsTest.ts
  apps/gauzy-e2e/src/e2e/PipelinesTest.ts
  apps/gauzy-e2e/src/e2e/TeamsTasksTest.ts
  apps/gauzy-e2e/src/support/Base/pagedata/GoalsPageData.ts
  apps/gauzy-e2e/src/support/Base/pagedata/OrganizationProjectsPageData.ts
  apps/gauzy-e2e/src/support/Base/pagedata/TeamsTasksPageData.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/AddEmployeeLevelPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/AddTasksPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/GoalsPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/ManageEmployeesPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationProjectsPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/OrganizationTeamsPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/PipelinesPageObject.ts
  apps/gauzy-e2e/src/support/Base/pageobjects/TeamsTasksPageObject.ts
  apps/gauzy-e2e/src/support/Base/pages/AddEmployeeLevel.po.ts
  apps/gauzy-e2e/src/support/Base/pages/AddTasks.po.ts
  apps/gauzy-e2e/src/support/Base/pages/Dashboard.po.ts
  apps/gauzy-e2e/src/support/Base/pages/Goals.po.ts
  apps/gauzy-e2e/src/support/Base/pages/ManageEmployees.po.ts
  apps/gauzy-e2e/src/support/Base/pages/OrganizationProjects.po.ts
  apps/gauzy-e2e/src/support/Base/pages/OrganizationTeams.po.ts
  apps/gauzy-e2e/src/support/Base/pages/Pipelines.po.ts
  apps/gauzy-e2e/src/support/Base/pages/TeamsTasks.po.ts
  apps/gauzy-e2e/src/support/Base/utils/api-utils.ts
  apps/gauzy-e2e/src/support/Base/utils/constants.ts
  apps/gauzy-e2e/src/support/Base/utils/index.ts
  apps/gauzy-e2e/src/support/Base/utils/util.ts
  apps/gauzy-e2e/src/support/commands.ts
  apps/gauzy-e2e/src/support/cyCommands.ts
  apps/gauzy-e2e/src/support/cypress-testing-library.d.ts
  apps/gauzy-e2e/src/support/index.ts
  apps/gauzy-e2e/tsconfig.json
  package.json
  yarn.lock
Labels: Test, Ready to be Merged

#71 GZY-396: fix the times per day in the timesheets ui are not calculated properly in the weekly tab
  packages/core/src/lib/time-tracking/time-log/time-log.service.ts
  packages/core/src/lib/time-tracking/time-log/time-log.utils.ts
  packages/ui-core/shared/src/lib/timesheet/gauzy-filters/gauzy-filters.component.ts
Labels: Bugfix, Ready to be Merged

#73 GZY-374: Fix missing time logs in counts
  apps/gauzy/src/app/pages/dashboard/time-tracking/time-tracking.component.ts
  packages/core/src/lib/time-tracking/statistic/statistic.service.ts
  packages/ui-core/shared/src/lib/timesheet/gauzy-filters/gauzy-filters.component.ts
Labels: Bugfix, Ready to be Merged

#74 GZY-409: Remove average income expenses and bonus columns from table
  apps/gauzy/src/app/pages/employees/employees.component.ts
Labels: Feature, Ready to be Merged

#75 GZY-408: Allow only one active time-tracking timer per user
  apps/gauzy/src/assets/workers/time-tracker.js
  packages/core/src/lib/time-tracking/time-log/commands/handlers/get-conflict-time-log.handler.ts
  packages/core/src/lib/time-tracking/time-log/commands/handlers/time-log-update.handler.ts
  packages/core/src/lib/time-tracking/time-log/time-log.utils.ts
  packages/core/src/lib/time-tracking/time-slot/utils.ts
  packages/core/src/lib/time-tracking/timer/timer.helper.ts
  packages/core/src/lib/time-tracking/timer/timer.service.ts
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
  packages/ui-core/shared/src/lib/time-tracker/time-tracker/time-tracker.component.ts
Labels: Feature, Test, Ready to be Merged

#77 GZY-381: Add synchronization state with the backend after stop confirmation
  packages/ui-core/core/src/lib/services/time-tracker/time-tracker.service.ts
Labels: Bugfix, Ready to be Merged
